version: '3'

# Project name (Used as prefix for container)
name: inception

# Services to run (Containers)
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress-files:/var/www/html
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-files:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-database:/var/lib/mysql
    restart: always
    networks:
      - inception


# Create the network (bridge by default)
networks:
  inception:
    driver: bridge

# Create volumes (VOLUMES_PATH exported by Makefile)
volumes:
  wordpress-files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUME_PATH}/wordpress
  wordpress-database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUME_PATH}/mariadb